name: CI/CD Pipeline

on:
  push:
    branches:
    - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Build project
        run: mvn clean package -DskipTests

      - name: Login to Amazon ECR Public
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/a1b7i2v0

      - name: Build Docker image
        run: docker build -t chatapp .

      - name: Tag Docker image for ECR
        run: docker tag chatapp:latest public.ecr.aws/a1b7i2v0/chatapp:latest

      - name: Push Docker image to ECR
        run: docker push public.ecr.aws/a1b7i2v0/chatapp:latest

